name = "MyVanillaPerfect"
author = "depocoder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1438c47c87b8f9ded87c34b7804abf56d483e2ae3ab7ec957a94c414410368e2"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
