name = "MyVanillaPerfect"
author = "depocoder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e164135ded04b1446c8e1c9076dae162d84db614dc7b0973e1fd6a734b92a10"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
